/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-my-portofolio-7dYZ9UZpDD2VyC-uk4CaDYwHwU0Ruqje",
  "version": "2020-11-20"
}

export default ebconfig;